// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d417f687ab0c81ed72bffbc5dace5f643369bb70/redux-promise/redux-promise.d.ts
declare namespace Redux {
	type PromiseAction<S> = (dispatch: Redux.Dispatch<S>, getState?: () => S) => any;

	interface Dispatch<S> {
		<R>(asyncAction: PromiseAction<S>): R;
	}
}

declare namespace ReduxPromise {
	export interface Promise extends Redux.Middleware {}
}

declare module "redux-promise" {
	var promise: ReduxPromise.Promise;
	export default promise;
}
